# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='adress',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='personal_number',
            field=models.CharField(max_length=11),
        ),
    ]
